name: Build Flowframes

on:
  push:
    branches: [ "gh-releases" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest 
    env:
      Solution_Name: Flowframes.sln
      Target: Flowframes
      Platform: x64
      GH_TOKEN: ${{ github.token }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build Flowframes
      run: |
        cd Code/
        nuget restore $env:Solution_name
        msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:Platform=$env:Platform -target:$env:Target
        cd ..
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Packaging Flowframes
      run: |
        cd Code\bin\x64\Release
        mkdir "FlowframesApp9999"
        mkdir "FlowframesApp9999/FlowframesData"
        mkdir "FlowframesApp9999/FlowframesData/pkgs"
        cp -r "../../../../pkgs/av" "FlowframesApp9999/FlowframesData\pkgs\av"
        cp -r ../../../../pkgs/dain-ncnn FlowframesApp9999/FlowframesData\pkgs\dain-ncnn
        cp -r "../../../../pkgs/licenses" "FlowframesApp9999/FlowframesData\pkgs\licenses"
        cp -r "../../../../pkgs/rife-cuda" "FlowframesApp9999/FlowframesData\pkgs\rife-cuda"
        cp -r "../../../../pkgs/rife-ncnn" "FlowframesApp9999/FlowframesData\pkgs\rife-ncnn"
        cp -r "../../../../pkgs/flavr-cuda" "FlowframesApp9999/FlowframesData\pkgs\flavr-cuda"
        cp -r "../../../../pkgs/xvfi-cuda" "FlowframesApp9999/FlowframesData\pkgs\xvfi-cuda"
        cp -r "../../../../pkgs/rife-ncnn-vs" "FlowframesApp9999/FlowframesData\pkgs\rife-ncnn-vs"
        echo "9999" >> "FlowframesApp9999/FlowframesData/ver.ini"
        cp -r Flowframes.exe "FlowframesApp9999"
        cd ../../../../Build
        ./7za.exe a FF-9999-Slim.7z -m0=flzma2 -mx5 "..\Code\bin\x64\Release\FlowframesApp9999"
        ls
        cd ..

    - name: Get build timestamp
      id: get-timestamp
      run: |
        echo "time=$(date -u "+%Y%m%d%H%M")" >> $GITHUB_OUTPUT

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ff-slim
        path: D:\a\flowframes\flowframes\Build\FF-9999-Slim.7z

    - name: Release
      run: |
        gh release create ff-${{steps.get-timestamp.outputs.time}} --generate-notes --prerelease --title "release"
        gh release upload ff-${{steps.get-timestamp.outputs.time}} D:\a\flowframes\flowframes\Build\FF-9999-Slim.7z
        
